services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: employees
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python wait-db.py && python manage.py migrate &&
             uvicorn employee_app.asgi:employees --host 0.0.0.0 --port 8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=employees
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DATABASE_URL=postgres://postgres:password@db:5432/employees
      - DB_PORT=5432

volumes:
  postgres_data:
