[phases.setup]
commands = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
commands = [
    "python manage.py migrate"
]

[phases.start]
cmd = "uvicorn employee_app.asgi:employees --host 0.0.0.0 --port 8080"
